version: 2

builds:
  - binary: "{{app_name}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X {{module_prefix}}/{{app_name}}/internal/version.ver={{.Version}}
        -X {{module_prefix}}/{{app_name}}/internal/version.commit={{.Commit}}
        -X {{module_prefix}}/{{app_name}}/internal/version.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{app_name}}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
